version: '3.8'
services:
  englishapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: englishapp
    restart: always
    networks:
       - proxy
    depends_on:
      - mysql
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.englishapp.rule=Host(`englishapp.alfredoacservices.com`)"
      - "traefik.http.routers.englishapp.entrypoints=web"
      - "traefik.http.services.englishapp.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.englishapp-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.englishapp.middlewares=englishapp-https-redirect"
      - "traefik.http.routers.englishapp-secure.entrypoints=websecure"
      - "traefik.http.routers.englishapp-secure.rule=Host(`englishapp.alfredoacservices.com`)"
      - "traefik.http.routers.englishapp-secure.tls=true"
      - "traefik.http.routers.englishapp-secure.tls.certresolver=letsencrypt"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:

networks:
  proxy:
    external: true
